/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package students.api;

import java.time.LocalDate;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        final Student carlinhos = Student.of(1L, "Carlinhos", LocalDate.now());
        System.out.println(carlinhos);

        final Instituition ufpe = Instituition.of(2L, "Universidade Federal de Pernambuco", LocalDate.now());
        System.out.println(ufpe);

    }
}
